name: Renovate App

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *' # every 4 hours

env:
  RENOVATE_VERSION: 43.248.0-full # renovate: datasource=docker depName=renovate packageName=ghcr.io/renovatebot/renovate

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3.12.0

      - name: Setup Node
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24

      - name: Add secrets to config
        run: |
          sed -i 's/%ARTICLES_WPML_KEY%/${{ secrets.ARTICLES_WPML_KEY }}/g' config.json
          sed -i 's/%ARTICLES_WPML_USER_ID%/${{ secrets.ARTICLES_WPML_USER_ID }}/g' config.json

      - name: Get Renovate app token
        uses: actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349 # v2.2.2
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PEM }}
          owner: ${{ github.repository_owner }}

      - name: Renovate
        uses: renovatebot/github-action@0a7b68676027570f113b1d6e7b69b231b56167ab # v46.2.3
        with:
          renovate-version: ${{ env.RENOVATE_VERSION }}
          configurationFile: config.json
          token: 'x-access-token:${{ steps.app-token.outputs.token }}'
          mount-docker-socket: true
        env:
          LOG_LEVEL: debug
