name: Validate Renovate config

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  preset:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - name: Validate config 
        run: |
          docker run \
            --entrypoint=renovate-config-validator \
            --volume "$(pwd):/tmp" \
            renovate/renovate:slim /tmp/config.json
